apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    greymatter.io/inject-sidecar-to: "8080"
  name: opa
  namespace: bookinfo
  labels:
    app: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
      name: opa
    spec:
      containers:
      - name: opa
        image: openpolicyagent/opa:0.46.1-envoy-rootless
        args: [
          "run",
          "--server",
          "--addr=localhost:8181",
          "--log-level=debug",
          "--diagnostic-addr=0.0.0.0:8282",
          "--set=plugins.envoy_ext_authz_grpc.addr=:9191",
          "--set=plugins.envoy_ext_authz_grpc.query=data.envoy.authz.allow",
          "--set=plugins.envoy_ext_authz_grpc.enable-reflection=true",
          "--set=decision_logs.console=true",
          "--ignore=.*",
          "/policy/policy.rego",
        ]
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
        volumeMounts:
        - readOnly: true
          mountPath: /policy
          name: opa-policy
      volumes:
      - name: opa-policy
        secret:
          secretName: opa-policy
---