# Copyright Istio Authors
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

### 1. greymatter.io does not use or need to expose services that are not related to the gm proxy sidecar
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongodb
#   labels:
#     app: mongodb
#     service: mongodb
# spec:
#   ports:
#     - port: 27017
#       name: mongo
#   selector:
#     app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  ### Change the name to prevent name collision in greymatter.io
  name: bookinfo-mongodb
  labels:
    app: bookinfo-mongodb
    version: v1
  ### 2. Annotation for greymatter.io sidecar injection
  annotations:
    greymatter.io/inject-sidecar-to: "27017"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookinfo-mongodb
      version: v1
  template:
    metadata:
      labels:
        app: bookinfo-mongodb
        version: v1
    spec:
      containers:
        - name: mongodb
          image: docker.io/istio/examples-bookinfo-mongodb:1.17.0
          imagePullPolicy: IfNotPresent
          ### 3. greymatter.io does not need to expose any ports on the application container
          ### Everything goes through the sidecar
          # ports:
          #   - containerPort: 27017
          volumeMounts:
            - name: data-db
              mountPath: /data/db
      volumes:
        - name: data-db
          emptyDir: {}
